name: Build and generate images then upload to GitHub Releases

on:
  push:
    branches:
    - master
  workflow_dispatch:
  # schedule:
  #   - cron:  '*/30 * * * *' # every 30min
jobs:
  generate_images:
    runs-on: macos-latest  # `webkit-font-smoothing` only works on macos
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      # We need full history to introspect created/updated:
      with:
        fetch-depth: 0
        path: master
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - uses: actions/cache@v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r master/requirements.txt
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: master/package-lock.json
    - name: Install Node.js dependencies
      run: |
        cd master
        npm ci
    - name: Generate images
      run: |
        cd master
        python generate.py
    - name: Release images
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        draft: false
        files: |
          master/dist/images/*
