name: Build and generate images then upload to GitHub Releases

on:
  push:
    branches:
    - master
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
jobs:
  generate_images:
    runs-on: macos-latest  # `webkit-font-smoothing` only works on macos
    env:
      VIEWPORT_SIZE: "400x300"  # Change this value as needed
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      # We need full history to introspect created/updated:
      with:
        fetch-depth: 0
        path: master
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - uses: actions/cache@v3
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r master/requirements.txt
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: master/package-lock.json
    - name: Install Node.js dependencies
      run: |
        cd master
        npm ci
    - name: Generate images
      run: |
        cd master
        python generate.py
    - name: Prepare release body
      id: release_body
      run: |
        cd master/dist/images
        REPO="${GITHUB_REPOSITORY}"
        echo "body<<EOF" >> $GITHUB_OUTPUT
        for f in *.png; do
          echo "- ![$f](https://github.com/${REPO}/releases/download/latest/$f)" >> $GITHUB_OUTPUT
        done
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Release images
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        draft: false
        body: ${{ steps.release_body.outputs.body }}
        files: |
          master/dist/images/*
